
app = "dark-crime-whatsapp-bot"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 5000
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["http"]
    port = 80
    
  [[services.ports]]
    handlers = ["http"]
    port = 443

[processes]
  app = "node index.js"

[deploy]
  strategy = "rolling"

[mounts]
  source = "auth_data"
  destination = "/app/auth"
